name: Run StyleLint

on:
  pull_request:
    paths:
      - "src/**/*.css"
  push:
    branches:
      - main

jobs:
  run_stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install stylelint
        run: |
          npm install --save-dev stylelint stylelint-config-standard

      - name: Run stylelint
        run: npx stylelint "**/*.css"
