name: Run HTMLHint

on:
  pull_request:
    paths:
      - "src/goats_tom/templates/**/*.html"
      - ".github/workflows/run_htmlhint.yaml"

  push:
    branches:
      - main

jobs:
  run_htmlhint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: latest

    - name: Install HTMLHint
      run: npm install htmlhint -g

    - name: Run HTMLHint
      run: htmlhint src
